[build]
  base    = "templates/04-Moderna"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *"
    X-Frame-Options = "ALLOWALL"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
